# Generated by Django 5.0.4 on 2024-04-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_anlysis_app', '0002_customuser_date_of_birth_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
